/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    LeTabs: typeof import('./components/LeTabs/index.vue')['default']
    LoginModal: typeof import('./components/layout/LoginModal.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    Types: typeof import('./components/LeTabs/types.vue')['default']
  }
}
